server:
  port: 8087

spring:
  application:
    name: eureka-client-feign-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

feign:
  hystrix:
    enabled: true