server:
  port: 8087

spring:
  zipkin:
    base-url: http://zipkin-server/
  sleuth:
    sampler:
      probability: 1
  application:
    name: eureka-client-feign-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

feign:
  hystrix:
    enabled: true